const pressToPlay = document.getElementById("press-to-play");
import Dino from './dino.min.js';
let image;
let levelZones = [];
if(localStorage.getItem("level") === null) {
    localStorage.setItem("level", 0);
}
class Levels extends Phaser.Scene {

    constructor() {
        super('Levels');
        pressToPlay.style.display = "none";
    }

    // Atlas generated by https://gammafp.github.io/atlas-packer-phaser/editor
    preload() {
        this.load.image("levels", "./src/assets/levels.png");
        this.load.image("train", "./src/assets/train.png");
    }

    create() {

        const changeScene = (level = 1, highScore = 150, speed = 1, cactusSpawn = [10000, 4000]) => {
            console.log(level + " " + (parseInt(localStorage.getItem("level")) + 1));
            if(level <= parseInt(localStorage.getItem("level")) + 1) {
                pressToPlay.style.display = "block";
                levelZones[0].off('pointerdown');
                levelZones[1].off('pointerdown');
                levelZones[2].off('pointerdown');
                levelZones[3].off('pointerdown');
                levelZones[4].off('pointerdown');
                levelZones[5].off('pointerdown');
                levelZones[6].off('pointerdown');
                levelZones[7].off('pointerdown');
                levelZones[8].off('pointerdown');
                levelZones[9].off('pointerdown');
                levelZones[10].off('pointerdown');
                levelZones[11].off('pointerdown');
                levelZones[12].off('pointerdown');
                levelZones[13].off('pointerdown');
                levelZones[14].off('pointerdown');
                levelZones[15].off('pointerdown');
                levelZones[16].off('pointerdown');
                levelZones[17].off('pointerdown');
                levelZones[18].off('pointerdown');
                levelZones[19].off('pointerdown');
                this.scene.start("Dino", {
                    speed: speed,
                    cactusSpawn: cactusSpawn,
                    desiredScore: highScore,
                    currentLevel: level
                });
                this.scene.remove("Levels");
            }
            // else {
            //     alert("This level is not yet available to you!")
            // }
        }
        image = this.add.image(500, 500, 'levels');

        levelZones.push(this.add.zone(50, 140, 100, 100).setDropZone());
        levelZones.push(this.add.zone(195, 140, 200, 100).setDropZone());
        levelZones.push(this.add.zone(450, 140, 100, 100).setDropZone());
        levelZones.push(this.add.zone(640, 140, 100, 100).setDropZone());
        levelZones.push(this.add.zone(800, 140, 100, 100).setDropZone());

        levelZones.push(this.add.zone(50, 270, 100, 100).setDropZone());
        levelZones.push(this.add.zone(230, 270, 100, 100).setDropZone());
        levelZones.push(this.add.zone(450, 270, 100, 100).setDropZone());
        levelZones.push(this.add.zone(640, 270, 100, 100).setDropZone());
        levelZones.push(this.add.zone(800, 270, 100, 100).setDropZone());

        levelZones.push(this.add.zone(50, 390, 100, 100).setDropZone());
        levelZones.push(this.add.zone(230, 390, 100, 100).setDropZone());
        levelZones.push(this.add.zone(450, 390, 100, 100).setDropZone());
        levelZones.push(this.add.zone(640, 390, 100, 100).setDropZone());
        levelZones.push(this.add.zone(800, 390, 100, 100).setDropZone());

        levelZones.push(this.add.zone(50, 510, 100, 100).setDropZone());
        levelZones.push(this.add.zone(240, 510, 100, 100).setDropZone());
        levelZones.push(this.add.zone(450, 510, 100, 100).setDropZone());
        levelZones.push(this.add.zone(640, 510, 100, 100).setDropZone());
        levelZones.push(this.add.zone(800, 510, 100, 100).setDropZone());

        switch (parseInt(localStorage.getItem("level"))) {
            case 0:
                this.add.image(50, 140, "train");
                break;
            case 1:
                this.add.image(195, 140, "train");
                break;
            case 2:
                this.add.image(450, 140, "train");
                break;
            case 3:
                this.add.image(640, 140, "train");
                break;
            case 4:
                this.add.image(800, 140, "train");
                break;
            case 5:
                this.add.image(50, 270, "train");
                break;
            case 6:
                this.add.image(230, 270, "train");
                break;
            case 7:
                this.add.image(450, 270, "train");
                break;
            case 8:
                this.add.image(640, 270, "train");
                break;
            case 9:
                this.add.image(800, 270, "train");
                break;
            case 10:
                this.add.image(50, 390, "train");
                break;
            case 11:
                this.add.image(230, 390, "train");
                break;
            case 12:
                this.add.image(450, 390, "train");
                break;
            case 13:
                this.add.image(640, 390, "train");
                break;
            case 14:
                this.add.image(800, 390, "train");
                break;
            case 15:
                this.add.image(50, 510, "train");
                break;
            case 16:
                this.add.image(240, 510, "train");
                break;
            case 17:
                this.add.image(450, 510, "train");
                break;
            case 18:
                this.add.image(640, 510, "train");
                break;
            case 19:
                this.add.image(800, 510, "train");
                break;
            case 20:
                if(!localStorage.getItem("hasWon")) {
                    localStorage.setItem("hasWon", "fax");
                    alert("You've beat the Orange Line!");
                }
                break;
            default:
                alert("💀 Unexpected Error!");
                break;
        }

        // Show levelZones; For development purposes only.
        // levelZones.forEach((showZone) => {
        //     var graphics = this.add.graphics();
        //     var color = 0xffff00;
        //     graphics.lineStyle(2, color);
        //     graphics.strokeRect(showZone.x + showZone.input.hitArea.x, showZone.y + showZone.input.hitArea.y, showZone.input.hitArea.width, showZone.input.hitArea.height);
        // });

        levelZones[0].off('pointerdown');
        levelZones[1].off('pointerdown');
        levelZones[2].off('pointerdown');
        levelZones[3].off('pointerdown');
        levelZones[4].off('pointerdown');
        levelZones[5].off('pointerdown');
        levelZones[6].off('pointerdown');
        levelZones[7].off('pointerdown');
        levelZones[8].off('pointerdown');
        levelZones[9].off('pointerdown');
        levelZones[10].off('pointerdown');
        levelZones[11].off('pointerdown');
        levelZones[12].off('pointerdown');
        levelZones[13].off('pointerdown');
        levelZones[14].off('pointerdown');
        levelZones[15].off('pointerdown');
        levelZones[16].off('pointerdown');
        levelZones[17].off('pointerdown');
        levelZones[18].off('pointerdown');
        levelZones[19].off('pointerdown');

        this.input.setPollAlways();

        levelZones[0].on('pointerdown', function () {
                changeScene(1);
        });
        levelZones[1].on('pointerdown', function() {
                changeScene(2, 350, 1.5, [15000, 4000]);
        });
        levelZones[2].on('pointerdown', function() {
            changeScene(3, 450, 2.5, [15000, 4000]);
        });
        levelZones[3].on('pointerdown', function() {
            changeScene(4, 550, 3.5, [15000, 4000]);
        });
        levelZones[4].on('pointerdown', function() {
            changeScene(5, 650, 4.5, [15000, 4000]);
        });
        levelZones[5].on('pointerdown', function() {
            changeScene(6, 750, 4.5, [15000, 4000]);
        });
        levelZones[6].on('pointerdown', function() {
            changeScene(7, 750, 4.5, [16000, 4000]);
        });
        levelZones[7].on('pointerdown', function() {
            changeScene(8, 750, 4.5, [17000, 4000]);
        });
        levelZones[8].on('pointerdown', function() {
            changeScene(9, 650, 4.5, [18000, 4000]);
        });
        levelZones[9].on('pointerdown', function() {
            changeScene(10, 650, 5, [18000, 4000]);
        });
        levelZones[10].on('pointerdown', function() {
            changeScene(11, 650, 5.5, [18000, 4000]);
        });
        levelZones[11].on('pointerdown', function() {
            changeScene(12, 650, 6, [18000, 4000]);
        });
        levelZones[12].on('pointerdown', function() {
            changeScene(13, 650, 6, [19000, 4000]);
        });
        levelZones[13].on('pointerdown', function() {
            changeScene(14, 650, 6, [20000, 4000]);
        });
        levelZones[14].on('pointerdown', function() {
            changeScene(15, 750, 6, [20000, 4000]);
        });
        levelZones[15].on('pointerdown', function() {
            changeScene(16, 850, 6, [20000, 4000]);
        });
        levelZones[16].on('pointerdown', function() {
            changeScene(17, 650, 6.5, [20000, 4000]);
        });
        levelZones[17].on('pointerdown', function() {
            changeScene(18, 750, 6.5, [21000, 4000]);
        });
        levelZones[18].on('pointerdown', function() {
            changeScene(19, 850, 7, [21000, 4000]);
        });
        levelZones[19].on('pointerdown', function() {
            changeScene(20, 1000, 7.5, [22000, 3000]);
        });
    }

    update(time, delta) {
    }

}

export default Levels;